name: Missinglinkink
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2866243540775031
title: 'Missing Link, Ink.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5592902041971684
  lightness: 0.810586805222556
  saturation: 0.8366290458943695
  rhythmicContrast: 0.8590088868513703
purpose: []
