name: Missinglinkink
favicon: null
layout_spectrum: 0
typography_spectrum: 0.11404
title: 'Missing Link, Ink.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74756f'
    - '#121214'
    - '#4d493d'
    - '#ccb4aa'
    - '#f8dddd'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
